routes/unauthenticated/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.html5 import EmailField, TelField
from wtforms.fields import PasswordField, SubmitField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

#
# def validate_time(form,field):
#     if field.data > form.data['org_close']:
#         raise ValidationError("Opening time can not be higher than closing time!")


class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):
    # User Details
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    mobile_number = TelField('Phone Number', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             validators=[DataRequired(), EqualTo('confirm_password', message="Passwords Must Match")])
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Register')

class PasswordResetForm(FlaskForm):
    password = PasswordField('Password',
                             validators=[DataRequired(), EqualTo('confirm_password', message="Passwords Must Match")])
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Change')

routes/unauthenticated/views.py
from flask import Blueprint, render_template, url_for, request, redirect, session, flash
from routes.unauthenticated.forms import LoginForm, RegisterForm, PasswordResetForm
from utils import *

unauthenticated = Blueprint('unauthenticated', __name__, template_folder='templates')


@unauthenticated.route('/Login', methods=['GET', 'POST'])
def login_page():
    if 'Logged_In' in session:
        return redirect(url_for('authenticated.my_workspaces_page'))

    login_form = LoginForm()
    #
    # Check if login request is valid
    if request.method == 'POST':
        if login_form.validate_on_submit():
            submitted_email = request.form.get('email').lower()
            submitted_passw = request.form.get('password')
            if attempt_login(submitted_email, submitted_passw):
                session['Logged_In'] = True
                session['Email'] = submitted_email
                return redirect(url_for('authenticated.my_workspaces_page'))
    return render_template('unauthenticated/html/login_page.html',
                           form=login_form)


@unauthenticated.route('/Register', methods=['GET', 'POST'])
def register_page():
    register_form = RegisterForm()
    print request.form.get('full_phone')
    #
    # Check if register request is valid
    if request.method == 'POST':
        if check_recaptcha():
            if register_form.validate_on_submit():
                user_id = register_user(
                    register_form.first_name.data,
                    register_form.last_name.data,
                    register_form.mobile_number.data,
                    register_form.password.data,
                    register_form.email.data
                )
                if user_id:
                    send_verification_email(user_id.key.id())
                    return redirect(url_for('unauthenticated.login_page'))

    return render_template('unauthenticated/html/register_page.html',
                           form=register_form)


@unauthenticated.route('/Verify', methods=['GET', 'POST'])
def verify_page():
    email = request.args.get('email')
    code = request.args.get('code')
    if email and code:
        verify_account(email, code)
    return redirect(url_for("unauthenticated.login_page"))


@unauthenticated.route('/ResetPassword', methods=['GET', 'POST'])
def reset_password_page():
    email = request.args.get('email')
    code = request.args.get('code')

    if not email or not code:
        flash('Invalid URL', 'danger')
        return redirect(url_for("unauthenticated.login_page"))

    user = verify_token(email, code)
    if not user:
        flash('Token is invalid or already used.', 'danger')
        return redirect(url_for("unauthenticated.login_page"))

    password_reset = PasswordResetForm()
    if request.method == "POST" and password_reset.validate_on_submit():
        if update_password(user, password_reset.password.data):
            flash('Password reset successful!', 'success')
        else:
            flash('Password reset unsuccessful.', 'danger')
        return redirect(url_for("unauthenticated.login_page"))

    return render_template('unauthenticated/html/reset_password.html',
                           form=password_reset)


@unauthenticated.route('/404PageNotFound', methods=['GET'])
def not_found_page():
    return render_template('unauthenticated/html/404.html')


@unauthenticated.route('/403ForbiddenAccess', methods=['GET'])
def forbidden_page():
    return render_template('unauthenticated/html/403.html')

routes/unauthenticated/templates/html/Base_Template.html
<!DOCTYPE html>
<html lang="en" class="gr__getbootstrap_com">
   <head>
      <title>{{page_title}}</title>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <link href="{{ url_for('static', filename='unauthenticated/CSS/base.css') }}" rel="stylesheet">

   </head>
   <body class="text-center">
      <form class="main-form" method="POST" >
         {% block before_flash %}
         {% endblock before_flash %}
         {% with messages = get_flashed_messages(with_categories=true) %}
         {% if messages %}
         {% for category, message in messages %}
         <div class="alert alert-{{category}} alert-dismissible fade show" role="alert" style="font-size: 14px;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
         </div>
         {% endfor %}
         {% endif %}
         {% endwith %}
         {% if form.errors %}
        {% for field in form %}
        {% if field.errors %}
        {% for error in field.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="font-size: 14px;">
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
           </button>
           {{error}}
        </div>
        {% endfor %}
        {% endif %}
        {% endfor %}
        {% endif %}
         {% block after_flash %}
         {% endblock after_flash %}
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      {% block script %}
      {% endblock script %}
   </body>
</html>

routes/unauthenticated/templates/html/login_page.html
{% extends "html/Base_Template.html" %}
{# Content that appears before flash #}
{% block before_flash %}
    <h1 class="h3 mb-3 font-weight-normal">{{page_title}}</h1>
    {{ form.hidden_tag()}}
    {{ form.email(class="form-control", placeholder="Email address", value=request.form.email)}}
    {{ form.password( class="form-control", placeholder="Password", value=request.form.password)}}
    {{ form.submit(class="btn btn-lg btn-primary btn-block", style="font-size: 1rem;")}}
{% endblock before_flash %}

{# Content that appears after alerts #}
{% block after_flash %}
    <div id="otherButtons">
        <a class="btn btn-primary" href="{{url_for('unauthenticated.register_page')}}">Register</a>
        <a class="btn btn-primary" id="passwordReset" >Reset Password?</a>
    </div>
{% endblock after_flash %}

{# Scripts #}
{% block script %}
{% endblock script %}

routes/unauthenticated/templates/html/register_page.html
{% extends "html/Base_Template.html" %}
{# Content that appears before flash #}
{% block before_flash %}
    <h1 class="h3 mb-3 font-weight-normal">{{page_title}}</h1>
    {{ form.hidden_tag()}}
    <div class="card-header">
        User Details
    </div>
    <div class="input-group mb-1">
        {{form.first_name(class="form-control", placeholder="First Name")}}
        {{form.last_name(class="form-control", placeholder="Last Name")}}
    </div>
    <div class="input-group mb-1">
        {{form.email(class="form-control", placeholder="Email")}}
        {{form.mobile_number(class="form-control", placeholder="Mobile Number")}}
    </div>
    <div class="input-group mb-1">
        {{form.password(class="form-control", placeholder="Password")}}
        {{form.confirm_password(class="form-control", placeholder="Confirm password")}}
    </div>
       <meter max="4" id="password-meter" style="margin: 0px"></meter>
        <div id="password-text" style="width: 100%; margin: 5px; font-size:13px;"></div>

    <div class="g-recaptcha" style="display: inline-block;  text-align: center;" data-sitekey="6LeTmZMUAAAAALtb3_C6JxpCVt0q6eu1M4wQqTrn"></div>
{% endblock before_flash %}

{# Content that appears after alerts #}
{% block after_flash %}
        {{ form.submit(class="btn btn-lg btn-primary btn-block", style="font-size: 1rem;")}}

    <div id="otherButtons">
        <div>Already have an account? <a href="{{url_for('unauthenticated.login_page')}}">Sign in!</a></div>
    </div>
{% endblock after_flash %}

{# Scripts #}
{% block script %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js"></script>
    <script>
   $(document).ready(function(){

       var strength = {
        0: "Bad",
        1: "Weak",
        2: "Good",
        3: "Strong",
        4: "Strong"
       }

       $('#password').keyup('click', function() {
           result = zxcvbn($('#password').val());
           $('#password-meter').val(result.score);
           $('#password-text').html("<strong>Password Strength: " + strength[result.score] + "</strong>");
       });

});
</script>
{% endblock script %}

routes/unauthenticated/templates/unauthenticated/html/Base_Template.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>{{page_title}}</title>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
       <!-- Bootstrap -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
       <!-- BaseCSS -->
       <link href="{{ url_for('static', filename='unauthenticated/CSS/base.css') }}" rel="stylesheet">

   </head>
   <body class="text-center">
      <form class="main-form" method="POST" >
         {% block before_flash %}
         {% endblock before_flash %}
         {% with messages = get_flashed_messages(with_categories=true) %}
         {% if messages %}
         {% for category, message in messages %}
         <div class="alert alert-{{category}} alert-dismissible fade show" role="alert" style="font-size: 14px;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
         </div>
         {% endfor %}
         {% endif %}
         {% endwith %}

          {% if form.errors %}
        {% for field in form %}
        {% if field.errors %}
        {% for error in field.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="font-size: 14px;">
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
           </button>
           {{error}}
        </div>
        {% endfor %}
        {% endif %}
        {% endfor %}
        {% endif %}

         {% block after_flash %}
         {% endblock after_flash %}
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      {% block script %}
      {% endblock script %}
   </body>
</html>

routes/unauthenticated/templates/unauthenticated/html/login_page.html
{% extends "unauthenticated/html/Base_Template.html" %}
{# Content that appears before flash #}
{% block before_flash %}
    <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
    {{ form.hidden_tag()}}
    {{ form.email(class="form-control", placeholder="Email address", value=request.form.email)}}
    {{ form.password( class="form-control", placeholder="Password", value=request.form.password)}}
    {{ form.submit(class="btn btn-lg btn-primary btn-block", style="font-size: 1rem;")}}
{% endblock before_flash %}

{# Content that appears after alerts #}
{% block after_flash %}
    <div id="otherButtons">
        <a class="btn btn-primary" href="{{url_for('unauthenticated.register_page')}}">Register</a>
        <a class="btn btn-primary" id="passwordReset" >Reset Password?</a>
    </div>
{% endblock after_flash %}

{# Scripts #}
{% block script %}
    <script>
   $(document).ready(function(){
       $('#passwordReset').on('click', function() {
           if ($('#email').val() != ""){
               console.log("fds");
               $.post("{{url_for('ajax.reset_password_email')}}",
               {
                   reset_email:$('#email').val(),
               },
               alert("Instructions on resetting your password has been sent to your email!")
           );
           } else {
              alert("Please type in your email address first!")
           }

       });
   });
</script>
{% endblock script %}

routes/unauthenticated/templates/unauthenticated/html/register_page.html
{% extends "unauthenticated/html/Base_Template.html" %}
{# Content that appears before flash #}
{% block before_flash %}
    <h1 class="h3 mb-3 font-weight-normal">Please provide your details.</h1>
    {{ form.hidden_tag()}}
    <div class="card-header">
        User Details
    </div>
    <div class="input-group mb-1">
        {{form.first_name(class="form-control", placeholder="First Name")}}
        {{form.last_name(class="form-control", placeholder="Last Name")}}
    </div>
    <div class="input-group mb-1">
        {% if request.args.get('email')  %}
        {{form.email(class="form-control", placeholder="Email", value=request.args.get('email'))}}
        {% else %}
        {{form.email(class="form-control", placeholder="Email")}}
        {% endif %}
        {{form.mobile_number(class="form-control", placeholder="Mobile Number")}}
    </div>
    <div class="input-group mb-1">
        {{form.password(class="form-control", placeholder="Password")}}
        {{form.confirm_password(class="form-control", placeholder="Confirm password")}}
    </div>
       <meter max="4" id="password-meter" style="margin: 0px"></meter>
        <div id="password-text" style="width: 100%; margin: 5px; font-size:13px;"></div>

    <div class="g-recaptcha" style="display: inline-block;  text-align: center;" data-sitekey="sitekey"></div>
{% endblock before_flash %}

{# Content that appears after alerts #}
{% block after_flash %}
        {{ form.submit(class="btn btn-lg btn-primary btn-block", style="font-size: 1rem;")}}

    <div id="otherButtons">
        <div>Already have an account? <a href="{{url_for('unauthenticated.login_page')}}">Sign in!</a></div>
    </div>
{% endblock after_flash %}

{# Scripts #}
{% block script %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js"></script>
    <script>
   $(document).ready(function(){

       var strength = {
        0: "Bad",
        1: "Weak",
        2: "Good",
        3: "Strong",
        4: "Strong"
       }

       $('#password').keyup('click', function() {
           result = zxcvbn($('#password').val());
           $('#password-meter').val(result.score);
           $('#password-text').html("<strong>Password Strength: " + strength[result.score] + "</strong>");
       });

});
</script>
{% endblock script %}

routes/unauthenticated/templates/unauthenticated/html/reset_password.html
{% extends "unauthenticated/html/Base_Template.html" %}
{# Content that appears before flash #}
{% block before_flash %}
        <h1 class="h3 mb-3 font-weight-normal">Enter New Password</h1>
    {{ form.hidden_tag()}}
            <div class="mb-2">
            {{form.password(class="form-control", placeholder="Password")}}
            </div>
            <div class="mb-2">
            {{form.confirm_password(class="form-control", placeholder="Confirm password")}}
            </div>
        <div class="form-row mb-2" style="justify-content: center">
            <div>
                <meter max="4" id="password-meter" style="width: 12em;"></meter>
                <div id="password-text" style="text-align: center; margin: 3px; font-size:13px;"></div>
            </div>
        </div>
        <div class="form-row"  style="justify-content:center">
        {{ form.submit(class="btn btn-lg btn-primary", style="font-size: 1rem;")}}
        </div>
{% endblock before_flash %}

{# Content that appears after alerts #}
{% block after_flash %}
<div id="otherButtons">
        <div>Already have an account? <a href="{{url_for('unauthenticated.login_page')}}">Sign in!</a></div>
    </div>
{% endblock after_flash %}

{# Scripts #}
{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js"></script>
    <script>
   $(document).ready(function(){

       var strength = {
        0: "Bad",
        1: "Weak",
        2: "Good",
        3: "Strong",
        4: "Strong"
       }

       $('#password').keyup('click', function() {
           result = zxcvbn($('#password').val());
           $('#password-meter').val(result.score);
           $('#password-text').html("<strong>Password Strength: " + strength[result.score] + "</strong>");
       });

});
</script>
{% endblock script %}