routes/authenticated/views.py
# coding=utf-8
import gc
import time
from functools import wraps
from app_statics import SIDEBAR
from flask import Blueprint, session, abort, redirect
from forms import *
from models import *
from routes.authenticated.utils import *
from routes.webhook.utils import call_webhook

authenticated = Blueprint('authenticated', __name__, template_folder='templates')


class DictMissKey(dict):
    # Create key if doesn't exist
    def __missing__(self, key):
        value = self[key] = type(self)()
        return value


class LoggedUser:
    def __init__(self, user_data, user_email, wks_data=None, projects_data=None, task_data=None, access_data=None):
        self.user_data = user_data
        self.user_key = user_data.key
        self.user_email = user_email

        if wks_data:
            self.wks_data = wks_data
            self.wks_key = wks_data.key
        if access_data:
            self.access_data = access_data
            self.access_key = access_data.key
        if projects_data:
            self.projects_data = projects_data
            self.projects_key = projects_data.key
        if task_data:
            self.task_data = task_data
            self.task_key = task_data.key

    def get_user_data(self):
        return self.user_data

    def get_wks_data(self):
        return self.wks_data

    def get_file_meta(self):
        return get_file_meta(self.wks_data)

    def get_project_data(self):
        return self.projects_data

    def get_task_data(self):
        return self.task_data

    def get_role(self):
        return self.access_data.role

    def get_permitted_workspaces(self):
        return get_workspaces(self.user_email)

    def get_tasks(self):
        return get_tasks(self.projects_key, self.get_role(), self.user_data.key.id())

    def get_invites(self):
        return get_invites(self.user_email)

    def get_projects(self, project_status):
        return get_projects(self.wks_key, self.get_role(), self.user_email, project_status, self.user_key.id())

    def get_all_projects(self):
        return get_all_projects(self.wks_key, self.get_role(), self.user_email, self.user_key.id())

    # This is used to get number on any task, not the one the page is on.
    def get_open_task_number(self, project_key):
        return get_open_task_number(project_key)

    def get_total_task_number(self, project_key):
        return get_total_task_number(project_key)

    def get_invites_number(self):
        return get_invites_number(self.user_email)

    def get_all_users(self):
        return get_all_users(self.wks_key)

    def get_total_allocated_minutes(self):
        return get_total_allocated_minutes(self.projects_key)

    def get_total_logged_minutes(self):
        return get_total_logged_minutes(self.projects_key)

    def get_username(self, log_developer):
        account_data = AccountDetails.get_by_id(log_developer)
        return account_data.first_name + " " + account_data.last_name

    def call_webhook(self):
        call_webhook(self.wks_key.id(), False)

    def get_prediction(self, functional_points):
        return self.projects_data.predict(functional_points)
        # return get_prediction(self.wks_key, functional_points)



# Permissions decorator, used and re-checked on every page load, first check login, account active, then workspace + role.
def login_required(roles=None):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if session.get('Logged_In', False):
                user_data = get_user_data_by_email(session.get('Email'))
                #
                # Check if account is active
                if not user_data.is_active:
                    session.clear()
                    gc.collect()
                    flash('Your account is no longer active.', 'danger')
                    return redirect(url_for('unauthenticated.login_page'))
                #
                wks_data = None
                projects_data = None
                task_data = None
                access_data = None
                if 'wks_id' in kwargs.keys():
                    if kwargs['wks_id'] == 0:
                        return redirect(url_for('authenticated.my_workspaces_page'))
                    wks_data = get_wks_data_by_id(kwargs['wks_id'])
                    if not wks_data:
                        abort(403)
                    access_data = check_access(wks_data.key, session.get('Email'))
                    # Check Permissions for workspace
                    if not access_data or access_data.role not in roles:
                        abort(403)
                    # Check Permission for project
                    if 'project_id' in kwargs.keys():
                        projects_data = get_project_data_by_id(kwargs['project_id'])
                        if not projects_data:
                            abort(403)
                        if not check_project_access(projects_data, session.get('Email'), access_data.role):
                            abort(403)
                    if 'task_id' in kwargs.keys():
                        task_data = get_task_data_by_id(kwargs['task_id'])
                        if not task_data:
                            abort(403)

                kwargs['user'] = LoggedUser(user_data, session.get('Email'), wks_data, projects_data, task_data,
                                            access_data)

            elif request.args.get("email") is not None:
                flash('Please login or sign up to access the requested page.', 'danger')
                return redirect(url_for('unauthenticated.register_page', email=request.args.get("email")))
            else:
                flash('Please login to access the requested page.', 'danger')
                abort(401)
            return func(*args, **kwargs)

        return wrapper

    return decorator


# Only Admin:

@authenticated.route('/Workspace/<int:wks_id>/Users', methods=['GET', 'POST'])
@login_required('admin')
def users_page(wks_id, **kwargs):
    new_user = NewUser()
    if request.method == "POST" and new_user.validate_on_submit():
        if add_user(kwargs['user'].wks_key, kwargs['user'].get_wks_data().workspace_name, new_user.user_email.data,
                    new_user.role.data):
            return redirect(url_for('authenticated.users_page', wks_id=wks_id))

    return render_template('authenticated/html/users_page.html',
                           form=new_user,
                           user_data=kwargs['user'],
                           wks_data=kwargs['user'].get_wks_data(),
                           SIDEBAR=SIDEBAR)


@authenticated.route('/Workspace/<int:wks_id>/Settings', methods=['GET', 'POST'])
@login_required('admin')
def wk_settings(wks_id, **kwargs):
    form = WKSettings()
    file_form = UploadHistorical()

    wk_data = kwargs['user'].get_wks_data()

    if request.method == "POST":
        if 'save' in request.form and file_form.validate_on_submit():
            if save_file(wk_data.key,file_form.file):
                flash('File Upload, recalibrate algorithm to use new data!', 'success')
                return redirect(url_for('authenticated.wk_settings', wks_id=wks_id))
            flash('Error occurred, please try again!', 'danger')
        if 'submit' in request.form and form.validate_on_submit():
            wk_data.workspace_name = form.workspace_name.data
            if form.enable_api.data == "False":
                wk_data.enable_api = False
            else:
                wk_data.enable_api = True

            if form.allow_dev_skills.data == "False":
                wk_data.allow_dev_skills = False
            else:
                wk_data.allow_dev_skills = True

            if form.enable_webhook.data == "False":
                wk_data.enable_webhook = False
            else:
                wk_data.enable_webhook = True

            wk_data.webhook_url = form.webhook_url.data

            if wk_data.put():
                flash('Details updated!', 'success')
                return redirect(url_for('authenticated.wk_settings', wks_id=wks_id))
            flash('Error occurred, please try again!', 'danger')

    form.workspace_name.data = wk_data.workspace_name
    form.allow_dev_skills.data = str(wk_data.allow_dev_skills)
    form.api_key.data = wk_data.api_key
    form.enable_api.data = str(wk_data.enable_api)
    form.webhook_url.data = wk_data.webhook_url
    form.enable_webhook.data = str(wk_data.enable_webhook)

    return render_template('authenticated/html/wk_settings.html',
                           form=form,
                           file_form=file_form,
                           user_data=kwargs['user'],
                           wks_data=kwargs['user'].get_wks_data(),
                           SIDEBAR=SIDEBAR)


# Manager or higher:
@authenticated.route('/Workspace/<int:wks_id>/Skills/<int:user_id>', methods=['GET', 'POST'])
@authenticated.route('/Workspace/<int:wks_id>/MySkills', methods=['GET', 'POST'])
@login_required({'admin', 'manager', 'developer'})
def my_skills_page(wks_id, user_id=None, **kwargs):
    if not kwargs['user'].get_wks_data().allow_dev_skills and kwargs['user'].get_role() == "developer":
        flash('Your Manager handles your skills, contact them to update!', 'warning')
        return redirect(url_for('authenticated.workspace_homepage', wks_id=wks_id))

    if user_id and (kwargs['user'].get_role() == "admin" or kwargs['user'].get_role() == "manager"):
        account_data = AccountDetails.get_by_id(user_id)
        look_up_key = account_data.key
        name = account_data.first_name
    else:
        look_up_key = kwargs['user'].user_key
        name = kwargs['user'].user_data.first_name

    new_skill = AddSkill()
    new_skill.skill_name.choices = [(skill.key.id(), skill.skill_name) for skill in
                                    SkillData.query(SkillData.Wks == kwargs['user'].wks_key

routes/authenticated/templates/authenticated/html/Base_Template.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>{{page_title}}</title>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <!-- FontAwesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
      <!-- BaseCSS -->
      <link href="{{ url_for('static', filename='authenticated/CSS/base.css') }}" rel="stylesheet">
       {% block header_content %}
       {% endblock header_content %}
   </head>
   <body id="page-top" class="sidebar-toggled">
      <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
         <a class="navbar-brand mr-1" href="{{url_for('authenticated.my_workspaces_page')}}">PM Tool</a>
         <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
         <i class="fas fa-bars"></i>
         </button>
         <!-- Positioning -->
         <form class="ml-auto">
         </form>
         <!-- Navbar -->
          {% include 'authenticated/html/includes/Navbar.html' %}
      </nav>
      <div id="wrapper">
         <!-- Sidebar -->
           {% include 'authenticated/html/includes/Sidebar.html' %}
         <div id="content-wrapper">
            <div class="container-fluid">
               <!-- Page Content -->
            <span style="display: flex;">
               <h1 style="margin-bottom: 0px;" >{{page_title}}</h1>
                {% include 'authenticated/html/includes/Alerts.html' %}
            </span>
               <hr>
            {% block page_content %}
            {% endblock page_content %}
            </div>
            <!-- /.container-fluid -->
         </div>
         <!-- /.content-wrapper -->
      </div>
      <!-- /#wrapper -->
      <!-- Bootstrap core JavaScript-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <!-- BaseJS -->
      <script src="{{ url_for('static', filename='authenticated/JS/base.js') }}" rel="stylesheet"></script>
      {% block script %}
      {% endblock script %}
   </body>
</html>

routes/authenticated/templates/authenticated/html/ganttchart.html
{% extends "authenticated/html/includes/Base_Template.html" %}

{% block header_content %}
    <link href="{{ url_for('static', filename='authenticated/CSS/ganttchart.css') }}" rel="stylesheet"
          xmlns="http://www.w3.org/1999/html">
    <script src="https://fullcalendar.io/releases/core/4.1.0/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/interaction/4.1.0/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/timeline/4.1.0/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/resource-common/4.1.0/main.min.js"></script>
    <script src="https://fullcalendar.io/releases/resource-timeline/4.1.0/main.min.js"></script>

    <link rel="stylesheet" href="https://fullcalendar.io/releases/core/4.1.0/main.min.css"/>
    <link rel="stylesheet" href="https://fullcalendar.io/releases/timeline/4.1.0/main.min.css"/>
    <link rel="stylesheet" href="https://fullcalendar.io/releases/resource-timeline/4.1.0/main.min.css"/>
{% endblock header_content %}

{% block page_header %}
    <h1 style="margin-bottom: 0px;">{{ project_data.project_name }} Gantt Chart</h1>
{% endblock page_header %}

{% block page_content %}
    <div class="container">
        <div class="my-page">
            <div id="gantt-chart-page">
                <div id='calendar'></div>
            </div>
        </div>
    </div>
    <a class="fa btn back-button" style="display: table;"
       href="{{ url_for('authenticated.view_project_page', wks_id=user_data.wks_key.id(), project_id=project_id) }}">
    <span style="display: table-cell; vertical-align: middle;">
        <i class="fas fa-arrow-left"></i>
    </span>
    </a>
{% endblock page_content %}
{# Scripts #}
{% block script %}
    <script>
        $(document).ready(function () {

            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                    plugins: ['interaction', 'resourceTimeline'],
                    timeZone: 'UTC',
                    header: {
                        left: 'prev,next',
                        center: 'title',
                        right: 'myTimelineDays,myTimelineWeek,myTimelineMonth'
                    },
                    defaultView: 'myTimelineWeek',
                    aspectRatio: 2,
                    views: {
                        myTimelineDays: {
                            type: 'resourceTimeline',
                            defaultDate: '2019-06-01',
                            duration: {year: 1},
                            slotDuration: {day: 1},
                            slotLabelFormat: [{month: 'long'}, {day: "2-digit"}],
                            buttonText: 'By Days'
                        },
                        myTimelineWeek: {
                            type: 'resourceTimeline',
                            duration: {year: 1},
                            slotDuration: {day: 7},
                            slotLabelFormat: [{month: 'short', year: 'numeric'}, {day: '2-digit'}],
                            buttonText: 'By Weeks',
                        },
                        myTimelineMonth: {
                            type: 'resourceTimeline',
                            duration: {year: 1},
                            slotDuration: {month: 1},
                            slotLabelFormat: [{month: 'short'}],
                            buttonText: 'By Months',
                        }
                    },
                    editable: false,
                    firstDay: 1,
                    resourceLabelText: 'Projects',
                    resources:{{ resources|tojson|e }},
                    events: {{ events|tojson|e }}
                });

            calendar.render();

        });


    </script>
{% endblock script %}

routes/authenticated/templates/authenticated/html/my_invites.html
{% extends "authenticated/html/includes/Base_Template.html" %}

{% block header_content %}
            <link href="{{ url_for('static', filename='authenticated/CSS/my_invites.css') }}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
            <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock header_content %}

{% block page_header %}
    <h1 style="margin-bottom: 0px;" >My Invites</h1>
{% endblock page_header %}

{% block page_content %}
    <div class="container">
    <div class="my-page">
    <div id="invites-list">
         <table id="myTable" class="table table-hover col-11 my-3">
             <thead class="thead-light">
                    <tr>
                        <th>Workspace Name</th>
                        <th>Role</th>
                        <th>View</th>
                    </tr>
                </thead>
              <tbody>
               {% for invite in user_data.get_invites()|sort(attribute='workspace_name') %}
                   <tr>
                        <td>{{ invite.workspace_name|capitalize}}</td>
                        <td>{{ invite.role|capitalize}}</td>
                        <td> <a href="{{ url_for('authenticated.open_invitation',email=session.get("Email"), code=invite.invitation_token) }}" class="badge badge-info">View</a> </td>
                   </tr>
               {% endfor %}
              </tbody>
         </table>
        </div>
        </div>
    </div>
    
{% endblock page_content %}

{# Scripts #}
{% block script %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>
{% endblock script %}

routes/authenticated/templates/authenticated/html/my_profile_page.html
{% extends "authenticated/html/includes/Base_Template.html" %}

{% block header_content %}
            <link href="{{ url_for('static', filename='authenticated/CSS/my_profile_page.css') }}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock header_content %}

{% block page_header %}
    <h1 style="margin-bottom: 0px;" >Your Account Details</h1>
{% endblock page_header %}

{% block page_content %}
    <div class="container">
            <div class="my-page">
            <form method="post">
                {{ form.hidden_tag()}}
                <div class="form-row" style="justify-content:center">
                    <div class="col-5 mb-2">
                    {{form.first_name(class="form-control", placeholder="First Name")}}
                    </div>
                    <div class="col-5 mb-2">
                    {{form.last_name(class="form-control", placeholder="Last Name")}}
                    </div>
                </div>
                <div class="form-row" style="justify-content:center">
                    <div class="col-5 mb-2">
                    {{form.email(class="form-control", placeholder="Email")}}
                    </div>
                    <div class="col-5 mb-2">
                    {{form.mobile_number(class="form-control", placeholder="Mobile Number")}}
                    </div>
                </div>
                <div class="form-row" style="justify-content:center">
                    <div class="col-5 mb-2">
                    {{form.password(class="form-control", placeholder="Password")}}
                    </div>
                    <div class="col-5 mb-2">
                    {{form.confirm_password(class="form-control", placeholder="Confirm password")}}
                    </div>
                </div>
                <div class="form-row mb-2" style="justify-content: center">
                    <div>
                        <meter max="4" id="password-meter"></meter>
                        <div id="password-text" style="text-align: center; margin: 3px; font-size:13px;"></div>
                    </div>
                </div>
                <div class="form-row"  style="justify-content:center">
                {{ form.submit(class="btn btn-lg btn-primary", style="font-size: 1rem;")}}
                </div>
            </form>
            </div>
    </div>
{% endblock page_content %}

{# Scripts #}
{% block script %}
   <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js"></script>
    <script>
   $(document).ready(function(){

       var strength = {
        0: "Bad",
        1: "Weak",
        2: "Good",
        3: "Strong",
        4: "Strong"
       }

       $('#password').keyup('click', function() {
           result = zxcvbn($('#password').val());
           $('#password-meter').val(result.score);
           $('#password-text').html("<strong>Password Strength: " + strength[result.score] + "</strong>");
       });

});
</script>
{% endblock script %}

routes/authenticated/templates/authenticated/html/my_skills_page.html
{% extends "authenticated/html/includes/Base_Template.html" %}

{% block header_content %}
    <link href="{{ url_for('static', filename='authenticated/CSS/my_skills_page.css') }}" rel="stylesheet"
          xmlns="http://www.w3.org/1999/html">
{% endblock header_content %}

{% block page_header %}
    <h1 style="margin-bottom: 0px;">{{ name }}'s Skills</h1>
{% endblock page_header %}

{% block page_content %}
    <div class="container">
        <div class="my-page">
            <div class="skills">
                <div class="col-11 my-3" style="margin: auto;">

                    <table class="table table-sm table-hover table-responsive-sm my-table">
                        <thead class="thead-light">
                        <tr>
                            <th width="40%" colspan="2">Skill</th>
                            <th width="60%">Expertise Scale</th>
                        </tr>
                        </thead>
                        <tbody id="body-logs">
                        {% set ranks = ["Novice", "Advanced Beginner", "Competent","Proficient","Expert"] %}
                        {% for skill in current_skills|sort(attribute='skill_id')%}
                        <tr>
                            <td style="vertical-align: middle;text-align: right">{{ skill.skill_name() }}</td>
                            <td style="vertical-align: middle;text-align: left">
                                <a data-skill-id="{{skill.key.id()}}" href="#" class="delete-skill badge badge-danger">Delete</a>
                            </td>
                            <td style="    padding-left: 1rem;    padding-right: 1rem;">
                                <span class="slidecontainer">
                                <div class="skill-name">
                                    {{ ranks[skill.skill_rating-1] }}
                                </div>
                                    <input data-skill-id="{{skill.key.id()}}" type="range" min="1" max="5" value="{{ skill.skill_rating }}" class="slider">
                                </span>
                            </td>
                        </tr>
                                    {%  endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <div class="modal" id="NewSkill" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <form method="post">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Please select or create new skill</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            {{ form.hidden_tag() }}
                            <div class="form-row" style="justify-content:center">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        {{ form.skill_name.label(class="input-group-text") }}
                                    </div>
                                    {{ form.skill_name(class="form-control") }}
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            {{ form.submit(class="btn btn-primary") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <a class="fa btn new-skill-button" data-toggle="modal" data-target="#NewSkill" href="javascript:void(0)">
    <span style="display: table-cell; vertical-align: middle;">
    <i class="fas fa-plus"></i>
    </span>
        </a>

    </div>

{% endblock page_content %}

{# Scripts #}
{% block script %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $("select").select2({
                tags: true,
                width: '70%'
            });

            $(".slider").on('change', function () {
                ranks = ["Novice", "Advanced Beginner", "Competent","Proficient","Expert"];
                $(this).parent().children("div").text(ranks[$(this).val()-1]);

                $.post("{{url_for('ajax.alter_skill',wks_id=wks_data.key.id())}}",
                    {"skill_id":$(this).attr("data-skill-id"), "rating":$(this).val()});

            });


            $(".delete-skill").on('click', function () {
                $.post("{{url_for('ajax.alter_skill',wks_id=wks_data.key.id())}}",
                    {"skill_id":$(this).attr("data-skill-id")});
                 $(this).closest("tr").remove();
            });




        });
    </script>
{% endblock script %}

routes/authenticated/templates/authenticated/html/open_invitation.html
{% extends "authenticated/html/includes/Base_Template.html" %}

{% block header_content %}
            <link href="{{ url_for('static', filename='authenticated/CSS/open_invitation.css') }}" rel="stylesheet" xmlns="http://www.w3.org/1999/html">
{% endblock header_content %}

{% block page_header %}
    <h1 style="margin-bottom: 0px;" >Invitation</h1>
{% endblock page_header %}

{% block page_content %}
    <div class="container">
    <div class="my-page" style="text-align: center;">
        <div class="page-text">You have been invited to join the following workspace:</div>
        <div class="workspace-name">{{ wks_data.workspace_name }}</div>
        <br>
        <form method="post" style="justify-content: center">
            <input type="submit" name="accepted" class="btn btn-lg accept-btn" value="Click here to accept the invite!">
        </form>
    </div>
    </div>
    
{% endblock page_content %}

{# Scripts #}
{% block script %}
    <script>

    </script>
{% endblock script %}

routes/authenticated/templates/authenticated/html/skills_matrix_page.html
{% extends "authenticated/html/includes/Base_Template.html" %}

{% block header_content %}
    <link href="{{ url_for('static', filename='authenticated/CSS/skills_matrix_page.css') }}" rel="stylesheet"
          xmlns="http://www.w3.org/1999/html">
{% endblock header_content %}

{% block page_header %}
    <h1 style="margin-bottom: 0px;">Skill Matrix</h1>
{% endblock page_header %}

{% block page_content %}
    <div class="container">
        <div class="my-page">
            <div id="skills">
                <div class="scrollable-table">
                    <table class="table-header-rotated" style="margin: auto;">
                        <thead>
                        <tr>
                            <!-- First column header is not rotated -->
                            <th></th>
                            <!-- Following headers are rotated -->
                            {% for skill in skill_data %}
                                <th class="rotate-45">
                                    <div><span>{{ skill[0] }}</span></div>
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for user, skill_item in user_skill.iteritems()|sort(attribute=0) %}
                            <tr>
                                <td class="row-header">
                                    <div>
                                        <a href="{{ url_for('authenticated.my_skills_page',wks_id=wks_data.key.id(), user_id=skill_item['id']) }}">{{ user }}</a>
                                    </div>
                                </td>
                                {% for skill in skill_data %}
                                    <td class="level-{{ skill_item[skill[0]] }}">{{ skill_item[skill[0]] }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div id="key">
        <table>
            <thead style="text-align: center">
            <th>Key</th>
            </thead>
            <tbody>
            <tr class="level-1">
                <td>1 - Novice</td>
            </tr>
            <tr class="level-2">
                <td>2 - Advanced Beginner</td>
            </tr>
            <tr class="level-3">
                <td>3 - Competent</td>
            </tr>
            <tr class="level-4">
                <td>4 - Proficient</td>
            </tr>
            <tr class="level-5">
                <td>5 - Expert</td>
            </tr>
            </tbody>
        </table>

    </div>

{% endblock page_content %}

{# Scripts #}
{% block script %}
    <script>

    </script>
{% endblock script %}